// apps/storobs-react-example/src/app/users/Users.tsx
import { useObservableState } from 'observable-hooks';
import { FC } from 'react';
import { UsersStateService } from './state/users-state.service';

const state = new UsersStateService();

const Users: FC = () => {
  const error = useObservableState(state.error$, null);
  const users = useObservableState(state.users$, []);
  const selectedUser = useObservableState(state.selectedUser$, null);
  const isLoading = useObservableState(state.isLoading$, false);

  const handleLoadUsers = () => {
    state.fetchUsers();
  };
  const handleSelectUser = (userId: string) => () => {
    state.selectUser(userId);
  };

  return (
    <div>
      <p>users works!</p>
      <button onClick={handleLoadUsers}>Load</button>
      {isLoading && <p>Loading...</p>}
      {error && <p>Error!</p>}
      {users.map((user) => (
        <pre
          key={user.id}
          style={{ cursor: 'pointer' }}
          onClick={handleSelectUser(user.id)}
        >
          {JSON.stringify(user, null, 2)}
        </pre>
      ))}
      {selectedUser && (
        <div>
          <p>Selected user:</p>
          <pre>{JSON.stringify(selectedUser, null, 2)}</pre>
        </div>
      )}
    </div>
  );
};

export default Users;

// apps/storobs-angular-example/src/app/users/users.component.ts
import { Component } from '@angular/core';
import { UsersStateService } from './state/users-state.service';

@Component({
  selector: 'manukpl-users',
  template: `
    <div>
      <p>users works!</p>
      <button (click)="loadUsers()">Load</button>
      <p *ngIf="isLoading$ | async">Loading...</p>
      <p *ngIf="error$ | async">Error!</p>
      <pre *ngFor="let user of users$ | async" (click)="selectUser(user.id)">{{
        user | json
      }}</pre>
      <div *ngIf="selectedUser$ | async as user">
        <p>Selected user:</p>
        <pre>{{ user | json }}</pre>
      </div>
    </div>
  `,
  styles: ['div > pre { cursor: pointer; }'],
})
export class UsersComponent {
  public readonly isLoading$ = this.usersState.isLoading$;
  public readonly users$ = this.usersState.users$;
  public readonly error$ = this.usersState.error$;
  public readonly selectedUser$ = this.usersState.selectedUser$;

  constructor(private readonly usersState: UsersStateService) {}

  public loadUsers(): void {
    this.usersState.fetchUsers();
  }

  public selectUser(userId: string) {
    this.usersState.selectUser(userId);
  }
}
